require 'iceboxer/version'
require 'iceboxer/icebox'
require 'iceboxer/template'
require 'iceboxer/old_version'
require 'iceboxer/closer'
require 'iceboxer/labeler'
require 'iceboxer/pullrequests'
require 'iceboxer/task'
